### ISSUE TITLE
URL Not Found

### ISSUE THREAD

**Issue by H1bertto** [KlemenS189/django-expiring-token#2] opened 2020-03-17 15:55 UTC
If I use:
`path('custom-url/', include('django_expiring_token.urls')),`
as authenticating URL, returns me 404 - Not Found

If I use:
`path('login/', obtain_auth_token),`
as authenticating URL, returns me, Token has no objects, because in the Tutorial it says to remove:
`'rest_framework.authtoken',`

Any suggestion?

**Comment by cr0wg4n** [comment] 2020-07-08 02:13
Hi @H1bertto, try to use `path('', include('django_expiring_token.urls')` and go to http://localhost:8000/login that works!

> If I use:
> `path('custom-url/', include('django_expiring_token.urls')),`
> as authenticating URL, returns me 404 - Not Found
> 
> If I use:
> `path('login/', obtain_auth_token),`
> as authenticating URL, returns me, Token has no objects, because in the Tutorial it says to remove:
> `'rest_framework.authtoken',`
> 
> Any suggestion?

**Comment by KlemenS189** [comment] 2021-03-10 19:25
Hi @H1bertto !
Sorry for the late reply.

Did you use the url `/custom-url/login/`? 
Also did you add `django_expiring_token` in settings? I have added a tests, and it works fine. Will try to replicate this in a local dev env.

**Comment by KlemenS189** [comment] 2021-03-10 19:58
Could not reproduce your issue with various scenarios. Closing this one.

**Closed as completed by KlemenS189** 2021-03-10 19:58 UTC
